# Generated by Django 4.2.3 on 2023-07-19 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_cart_product_list_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='order.cart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='item_count',
            field=models.IntegerField(default=1),
        ),
    ]
