# Generated by Django 4.2.3 on 2023-07-21 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_product_desription_product_product_description'),
        ('order', '0004_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='color_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.colorvariant'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.sizevariant'),
        ),
    ]
